config/routes.rb
Rails.application.routes.draw do

#ゲストログイン 
  devise_scope :user do
    get 'user/guest_sign_in', to: 'publics/sessions#guest_sign_in'
  end
 
 
#ユーザー側
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'publics/sessions',
    registrations: 'publics/registrations'
  }
  
  #退会確認画面
  get '/users/:id/unsubscribe' => 'publics/users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'publics/users#withdrawal', as: 'withdrawal'

  root to: 'publics/homes#top'
  get '/announcements' => 'publics/homes#announcements'
  scope module: :publics do
    resources :users, only:[:index, :show, :edit, :update] do
      resources :posts, only:[:index]
      member do
        get :confirm
        get :favorites
      end
    end
    
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]do
       resources :comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy]
    end
    
    post "search" => "searches#search"
    get "search_tag"=>"posts#search_tag"
  end
  
  
  
#管理者側
  devise_for :admins, skip: [:registrations, :passwords], 
    controllers: {
    sessions: 'admins/sessions'
  }
  
  namespace :admins do
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
    
    resources :users, only:[:index, :show]
    resources :announcements, only:[:index, :new, :create, :show, :edit, :update, :destroy]
    resources :posts, only:[:index, :show, :destroy]do
      resources :comments, only: [:destroy]
    end
  end
  
  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :title, presence: true, on: :publicize
  validates :content, presence: true, on: :publicize
  
  
  has_one_attached :image
  has_many_attached :addition_images
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('hukucity/app/assets/images/no_image_irasutoya.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :image, presence: true, on: :publicize
  validate :validate_number_of_files
  
  def validate_number_of_files
    return if addition_images.length <= 4
    errors.add(:addition_images, "に入力できる画像は4つまでです。")
  end
  
  
  belongs_to :user
 
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, keyword)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{keyword}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{keyword}%")
    else
      @post = Post.all
    end
  end
  
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  
  def index
    @posts = Post.where(is_draft: :false).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path
    else
      render 'show'
    end
  end



end

app/controllers/publics/comments_controller.rb
class Publics::CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end


end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to post_path(@post)
  end



end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    @announcements = Announcement.order(created_at: :desc).first(3)
  end
  
  def announcements
    @announcements = Announcement.order(created_at: :desc).page(params[:page]).per(3)
  end
  
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search_tag]
  
  
  def new
    @post = Post.new
  end
  
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #タグを作るには「,」をつける
    tag_list = params[:post][:name].split(',')
    
    #投稿公開
    if params[:release]
      @post.is_draft = false
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "投稿を公開しました！"
        redirect_to user_posts_path(current_user)
      else
        render :new
      end
    #下書き
    elsif params[:draft]
      @post.is_draft = true
      if @post.update(is_draft: :true)
        @post.save_tag(tag_list)
        flash[:notice] = "下書きを保存しました！"
        redirect_to confirm_user_path(current_user)
      else
        render :new
      end
    end
  end
  
  
  def index
    @posts = Post.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
    @comment = Comment.new
  end


  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end
  
  
  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
      
  # ①下書きを公開する場合
    if params[:publicize_draft]
      @post.attributes = post_params.merge(is_draft: false)
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "公開しました！"
        redirect_to user_posts_path(current_user)
      else
        @post.is_draft = true
        render :edit
      end
      
  # ②公開済みの投稿を更新する場合
    elsif params[:update_post]
      @post.attributes = post_params
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        redirect_to user_posts_path(current_user)
      else
        render :edit
      end   
      
  # ③下書きを下書きに更新する場合
    else
      if @post.update(post_params)
        @post.save_tag(tag_list)
        redirect_to confirm_user_path(current_user)
      else
        render :edit
      end    
      
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "削除しました。"
      redirect_to posts_path, status: :see_other
    else
      render 'edit'
    end
  end
  
  
  def search_tag
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @posts = @tag.posts.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
  end
  
  
  
   private
  
  def post_params
    params.require(:post).permit(:image, :title, :content, :is_draft, addition_images: [] )
  end
  
  
  
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :email, :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/searches_controller.rb
class Publics::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "ユーザー名"
      @users = User.looks(params[:search], params[:keyword]).where(is_deleted: false)
    else
      @posts = Post.looks(params[:search], params[:keyword]).where(is_draft: false)#改行
                  .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc)
    end
  end
  
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path(user)
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


   protected

  #退会後のログインを阻止
   def reject_user
    @user = User.find_by(name: params[:user][:email])
    if @user 
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_
      else
        flash[:notice] = "項目を入力してください"
      end
    end
   end
   

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
    @users = User.where(is_deleted: false)
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(is_draft: :false).order(created_at: :desc).page(params[:page]).per(8)
  end

  def edit
    user = User.find(params[:id])
     unless user.id == current_user.id
    redirect_to user_path(current_user.id)
     end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to user_path(@user)
     else
      render :edit
     end
  end
  
  def unsubscribe
    @user = User.find(params[:id])
  end
  
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  
  def confirm
    @posts = current_user.posts.where(is_draft: :true)
  end
  
  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @posts = Post.find(favorites)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:profile_image, :name, :name_kana, :nickname, :telephone_number, :email,)
  end
  
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/publics/comments_helper.rb
module Publics::CommentsHelper
end

app/helpers/publics/favorites_helper.rb
module Publics::FavoritesHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

app/helpers/publics/searches_helper.rb
module Publics::SearchesHelper
end

app/views/publics/posts/_form_favorite.html.erb
  <% if post.favorited_by?(current_user) %>
    <p>
      <%= button_to post_favorites_path(post), method: :delete do %>
        ♥<%= post.favorites.count %> いいね
      <% end %>
    </p>
  <% else %>
    <p>
      <%= button_to post_favorites_path(post) do %>
        ♡<%= post.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/publics/posts/_index.html.erb
  <table>
    
    <% posts.each do |post| %>
      <tr>
        <td>
          <%= link_to post_path(post.id), class: "text-dark text-decoration-none" do %>
            <%= image_tag post.image, size: "100x100" %>
            【<%= post.title.truncate(10) %>】
          <% end %>
        </td>
        <td><%= post.tags.map(&:name).join(',') %></td>
      </tr>
    <% end %>
  </table>
 

app/views/publics/posts/_tag_list.html.erb
   <h5>タグ検索</h5>
    
  
    <% tag_list.each do |list|%>
        <%= link_to list.name, search_tag_path(tag_id: list.id), class: "text-decoration-none" %>
        <%="(#{list.posts.count})" %>
    <% end %>
 
     

app/views/publics/posts/edit.html.erb
<div class='container'>

  <div class="row mt-3">
    <div class="col-lg-3">
      <h4 class="m-3" >編集ページ</h4>
    </div>
  </div>
  
  
    <%= form_with model:@post do |f| %>
    
    　   <div class="form-group">
          <label class="text-secondary">タイトル</label><br>
          <%= f.text_field :title, :size=>"60" %>
        </div>
        
    　   <div class="form-group">
          <label class="text-secondary">画像</label><br>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
    　 
        <div class="form-group">
          <label class="text-secondary">投稿内容</label><br>
          <%= f.text_area :content, class: 'form-control',size: "20x10" %>
        </div>
          
        <div class="form-group">
          <label class="text-secondary">タグ (,で区切ると複数タグ登録できます)</label><br>
          <%= f.text_field :name, value: @tag_list, class:"form-control"%>
        </div>
      
        
      <div class="d-flex justify-content-end m-5">
          <% if @post.is_draft == true %>
           <div class="p-2">
            <%= f.submit "下書きを公開", :name => 'publicize_draft', class:'mr-5 btn btn-sm btn-warning text-light' %>
           </div>
           <div class="p-2">
            <%= f.submit "下書きを更新", :name => 'update_draft', class:'mr-5 btn btn-sm btn-outline-secondary' %>
           </div>
          <% else %>
           <div class="p-2">
            <%= f.submit "投稿を更新", :name => 'update_post', class:'btn btn-sm btn-warning text-light' %>
           </div>
           <div class="p-2">
            <%= link_to "この投稿を削除する", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
           </div>
          <% end %>
        </div>
    
    <% end %>
  
</div>

app/views/publics/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-5">
      <%= render 'tag_list', tag_list: @tag_list %>
    </div> 
    
    <div class="col-md-8 offset-md-1 mt-5">
      <h5>みんなの投稿一覧</h5>
        <%= render 'index', posts: @posts %>
        <%= paginate @posts %>
    </div>  
      
  </div>
</div>
      
   

app/views/publics/posts/new.html.erb
<div class='container'>

  <div class="row mt-3">
    <div class="col-lg-3">
      <h4 class="m-3" >アイデア投稿</h4>
    </div>
  </div>
    
    
      <%= form_with model:@post do |f| %>
    　   <div class="form-group">
          <label class="text-secondary">タイトル</label><br>
          <%= f.text_field :title, :size=>"60" %>
        </div>
        
    　   <div class="form-group">
          <label class="text-secondary">画像</label><br>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
    　 
        <div class="form-group">
          <label class="text-secondary">投稿内容</label><br>
          <%= f.text_area :content, class: 'form-control',size: "20x10" %>
        </div>
          
        <div class="form-group">
          <label class="text-secondary">タグ (,で区切ると複数タグ登録できます)</label><br>
          <%= f.text_field :name,class:"form-control"%>
        </div>
        
        
  <div class="row float-end">
    <div class="m-5">
      <%= f.submit '投稿を公開', :name => 'release', class: 'mr-5 btn btn-sm btn-warning text-white' %>
      <%= f.submit '下書きに保存', :name => 'draft', class: 'mr-5 btn btn-sm btn-outline-secondary' %>
    </div>
  </div>
        
     <% end %>
    
</div> 

app/views/publics/posts/search_tag.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-3 mt-5">  
     <%= render 'tag_list', tag_list: @tag_list %>
    </div>  
    <div class="col-md-8 offset-md-1 mt-5">
    <h5><%=@tag.name%>の検索結果</h5>
     <%= render 'index', posts: @posts %>
    </div>  
  </div>

</div>

app/views/publics/posts/show.html.erb
<div class='container'>
 
  <div class="row mt-5">
    <div class="col-lg-4">
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, size: "50x50" %>
      <% else %>
        <%= image_tag 'no_image_irasutoya', size: "50x50" %>
      <% end %>
      
      <%= @user.nickname %>
    </div>
    
    <div class="col-lg-2 offset-lg-6" >
      <% if @post.user == current_user %>
        <% if @post.is_draft == true %>
          <%= link_to "この下書きを編集する", edit_post_path(@post.id), class: "btn btn-sm btn-success" %>
        <% else %>
          <%= link_to "この投稿を編集する", edit_post_path(@post.id), class: "btn btn-sm btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div> 

  <div class="row mt-5">
    <div class="col-lg-4" > 
      <%= image_tag @post.image, size: "300x300" %>
      
  <% if @post.is_draft == false %>
     
        <%= render 'form_favorite', post: @post %>
     
    
     
      <h4>【<%= @post.title %>】</h4>
      <p><%= @post.content %></p>
        <%= @post.tags.map(&:name).join(',') %>
    </div>
  </div> 
  
  <div class="row mt-5">
    <div class="col-lg-4 offset-lg-4">
      <% @post.comments.each do |comment| %>
        <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image, size: "50x50" %>
        <% else %>
          <%= image_tag 'no_image_irasutoya', size: "50x50" %>
        <% end %>
       <%= comment.user.name %>
       <%= comment.created_at.strftime('%Y/%m/%d') %>
       <%= comment.comment %>
      <% end %>
    </div>
    <div>
      <%= form_with model: [@post, @comment] do |f| %>
        <%= f.text_area :comment, :size=>"30", placeholder: "この投稿にコメントする" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
  </div> 
  
 <% end %>
  
</div>