config/routes.rb
Rails.application.routes.draw do

#ゲストログイン 
  devise_scope :user do
    get 'user/guest_sign_in', to: 'publics/sessions#guest_sign_in'
  end
 
 
#ユーザー側
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'publics/sessions',
    registrations: 'publics/registrations'
  }
  
  #退会確認画面
  get '/users/:id/unsubscribe' => 'publics/users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'publics/users#withdrawal', as: 'withdrawal'

  root to: 'publics/homes#top'
  get '/announcements' => 'publics/homes#announcements'
  scope module: :publics do
    resources :users, only:[:index, :show, :edit, :update] do
      resources :posts, only:[:index]
      member do
        get :confirm
        get :favorites
      end
    end
    
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]do
       resources :comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy]
    end
    
    post "search" => "searches#search"
    get "search_tag"=>"posts#search_tag"
  end
  
  
  
#管理者側
  devise_for :admins, skip: [:registrations, :passwords], 
    controllers: {
    sessions: 'admins/sessions'
  }
  
  namespace :admins do
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
    
    resources :users, only:[:index, :show]
    resources :announcements, only:[:index, :new, :create, :show, :edit, :update, :destroy]
    resources :posts, only:[:index, :show, :destroy]do
      resources :comments, only: [:destroy]
    end
  end
  
  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      user.name_kana = 'ゲスト' 
      user.nickname = 'ゲスト'
      user.telephone_number = '00000000001' 
    end
  end
  
  #退会済みユーザーのログイン制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  validates :name, presence: true
  validates :name_kana, presence: true, format: { with: /\A[ァ-ヴー]+\z/u }
  validates :nickname, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  
  

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('hukucity/app/assets/images/no_image_irasutoya.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
  def self.looks(search, keyword)
    if search == "perfect_match"
      @user = User.where("nickname LIKE?", "#{keyword}")
    elsif search == "partial_match"
      @user = User.where("nickname LIKE?","%#{keyword}%")
    else
      @user = User.all
    end
  end
  

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  
  def index
    @user = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end
  
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: !@user.is_deleted) #!をつけて、true/falseを反転
 
        if @user.is_deleted
           flash[:notice] = "退会処理を実行いたしました"
        else
           flash[:notice] = "有効にします"
        end
    redirect_to admins_users_path
  end
  
end

app/controllers/publics/comments_controller.rb
class Publics::CommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end


end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/favorites_controller.rb
class Publics::FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to post_path(@post)
  end



end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  def top
    @announcements = Announcement.order(created_at: :desc).first(3)
  end
  
  def announcements
    @announcements = Announcement.order(created_at: :desc).page(params[:page]).per(3)
  end
  
end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search_tag]
  
  
  def new
    @post = Post.new
  end
  
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #タグを作るには「,」をつける
    tag_list = params[:post][:name].split(',')
    
    #投稿公開
    if params[:release]
      @post.is_draft = false
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "投稿を公開しました！"
        redirect_to user_posts_path(current_user)
      else
        render :new
      end
    #下書き
    elsif params[:draft]
      @post.is_draft = true
      if @post.update(is_draft: :true)
        @post.save_tag(tag_list)
        flash[:notice] = "下書きを保存しました！"
        redirect_to confirm_user_path(current_user)
      else
        render :new
      end
    end
  end
  
  
  def index
    @posts = Post.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
    @comment = Comment.new
  end


  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end
  
  
  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
      
  # ①下書きを公開する場合
    if params[:publicize_draft]
      @post.attributes = post_params.merge(is_draft: false)
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "公開しました！"
        redirect_to user_posts_path(current_user)
      else
        @post.is_draft = true
        render :edit
      end
      
  # ②公開済みの投稿を更新する場合
    elsif params[:update_post]
      @post.attributes = post_params
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        redirect_to user_posts_path(current_user)
      else
        render :edit
      end   
      
  # ③下書きを下書きに更新する場合
    else
      if @post.update(post_params)
        @post.save_tag(tag_list)
        redirect_to confirm_user_path(current_user)
      else
        render :edit
      end    
      
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "削除しました。"
      redirect_to posts_path, status: :see_other
    else
      render 'edit'
    end
  end
  
  
  def search_tag
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @posts = @tag.posts.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
  end
  
  
  
   private
  
  def post_params
    params.require(:post).permit(:image, :title, :content, :is_draft, addition_images: [] )
  end
  
  
  
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :email, :telephone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/searches_controller.rb
class Publics::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "ユーザー名"
      @users = User.looks(params[:search], params[:keyword]).where(is_deleted: false)
    else
      @posts = Post.looks(params[:search], params[:keyword]).where(is_draft: false)#改行
                  .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc)
    end
  end
  
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path(user)
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


   protected

  #退会後のログインを阻止
   def reject_user
    @user = User.find_by(name: params[:user][:email])
    if @user 
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration_
      else
        flash[:notice] = "項目を入力してください"
      end
    end
   end
   

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Publics::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/users_controller.rb
class Publics::UsersController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
    @users = User.where(is_deleted: false)
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(is_draft: :false).order(created_at: :desc).page(params[:page]).per(8)
  end

  def edit
    user = User.find(params[:id])
     unless user.id == current_user.id
    redirect_to user_path(current_user.id)
     end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      redirect_to user_path(@user)
     else
      render :edit
     end
  end
  
  def unsubscribe
    @user = User.find(params[:id])
  end
  
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  
  def confirm
    @posts = current_user.posts.where(is_draft: :true)
  end
  
  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @posts = Post.find(favorites)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:profile_image, :name, :name_kana, :nickname, :telephone_number, :email,)
  end
  
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/publics/comments_helper.rb
module Publics::CommentsHelper
end

app/helpers/publics/favorites_helper.rb
module Publics::FavoritesHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

app/helpers/publics/searches_helper.rb
module Publics::SearchesHelper
end

app/views/publics/users/confirm.html.erb
 <div class="notice"><%= flash[:notice] %></div>
 
 <div class="container">
  
  <div class="row mt-5">
    <div class="col-lg-4 offset-1">
      <h5>下書き一覧</h5>
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col-lg-9 mx-auto">
      <%= render 'publics/posts/index', posts: @posts %>
    </div>
  </div>
  
</div>

app/views/publics/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-md-3">
      <h4 class="m-5">会員情報編集</h4>
    </div>
  </div>
  
  <%= form_with model:@user, local:true do |f| %>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>プロフィール画像</label>
    </div>
    <div class="col-sm-4">
      <%= f.file_field :profile_image, accept: "image/*" %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>氏名</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :name %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>カナ</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :name_kana %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>ニックネーム</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :nickname %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>電話番号</label>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :telephone_number %>
    </div>
  </div>
  
  <div class="form-group row">
    <div class="col-sm-3">
      <label>メールアドレス</label>
    </div>
    <div class="col-sm-4">
      <%= f.email_field :email %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-2 m-3">
      <%= f.submit "編集内容を保存", class: 'btn btn-sm btn-block btn-success' %>
    </div>
    <div class="col-sm-2 m-3">
        <%= link_to "退会する", unsubscribe_path(@user), class: "btn btn-sm btn-block btn-danger" %>
    </div>
  </div>
    
  <% end %>
   
  </div>
</div>

app/views/publics/users/favorites.html.erb
<div class="container">
  
  <div class="row mt-5">
    <div class="col-lg-4 offset-1">
    <h5>いいねした投稿一覧</h5>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-lg-9 mx-auto">
      <%= render 'publics/posts/index', posts: @posts %>
    </div>
  </div>
  
</div>
     

app/views/publics/users/index.html.erb
 <div class="container">
  
  <div class="row">
    <h5 class="mt-5">ユーザー</h5>
  </div>

  <div class="col-md-8 offset-md-1 mt-2">  
    <table class="table table-striped table-light table-hover">
     
     <% @users.each do |user| %>
      <tr>
        <td>
          <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, size: "50x50" %>
          <% else %>
            <%= image_tag 'no_image_irasutoya', size: "50x50" %>
          <% end %>
        </td>
        <td><%= user.nickname %></td>
        <td>
          <div class="text-right">
            <%= link_to user_path(user.id), class: 'mr-5 btn btn-sm btn-outline-secondary' do %>
              <i class="fa-solid fa-arrow-up-right-from-square">&nbsp;このユーザーの投稿を見る</i><% end %>
          </div>
        </td>
      </tr>
     <% end %>

    </table>
  </div>
 
 

app/views/publics/users/show.html.erb
<div class="container">
  
  <div class='row'>
    <div class="col-md-4">
      <h4 class="m-5"><%= @user.nickname %>さん</h4>
    </div>
  </div>
  
  <div class='row'>
    <div class="col-md-4">
          <% if @user.profile_image.attached? %>
           <%= image_tag @user.profile_image, size: "200x200" %>
          <% else %>
           <%= image_tag 'no_image_irasutoya', size: "200x200" %>
          <% end %>
          
        <div class='mt-5 mb-5'>
          <% if @user == current_user %>
            <% if @user.name != "ゲスト" %>
              <%= link_to "会員情報を編集する", edit_user_path(@user), class: "btn btn-sm btn-block btn-info text-light" %></br>
            <% end %>
              <%= link_to "いいねした投稿をみる", favorites_user_path(@user), class: "btn btn-sm btn-block btn-success" %></br>
              <%= link_to "下書き一覧", confirm_user_path(@user), class: "btn btn-sm btn-block btn-warning text-light" %>
          <% end %>
        </div> 
    </div> 
    
    <div class="col-md-7 offset-1">
      <h5 class ="mb-5">投稿一覧</h5>
        <%= render 'publics/posts/index', posts: @posts %>
        <%= paginate @posts %>
    </div>
  </div>
  
</div>

app/views/publics/users/unsubscribe.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

        <div class="row justify-content-center">
          <h4 class="m-5">
            <strong>退会手続き</strong>
          </h4>
          <p class="text-center mb-5">
          退会すると、これまでの投稿が閲覧できなくなります。</br>
          再度ご利用をいただく場合には、新規登録のお手続きが必要になります。</br>
          本当に退会してよろしいですか？</br>
          退会する場合は、「退会する」をクリックしてください。</p>
        </div>
        <div class="row justify-content-center mb-5">
          <p><%= link_to '退会しない', user_path(current_user), class: "btn btn-sm btn-primary" %>&emsp;</p>
          <p><%= button_to '退会する', withdrawal_path, method: :patch, class: "btn btn-sm btn-danger" %></p>
        </div>
      </div>
    </div>
  </div>
</main>