config/routes.rb
Rails.application.routes.draw do

#ゲストログイン 
  devise_scope :user do
    get 'user/guest_sign_in', to: 'publics/sessions#guest_sign_in'
  end
 
 
#ユーザー側
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'publics/sessions',
    registrations: 'publics/registrations'
  }
  
  #退会確認画面
  get '/users/:id/unsubscribe' => 'publics/users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'publics/users#withdrawal', as: 'withdrawal'

  root to: 'publics/homes#top'
  get '/announcements' => 'publics/homes#announcements'
  scope module: :publics do
    resources :users, only:[:index, :show, :edit, :update] do
      resources :posts, only:[:index]
      member do
        get :confirm
        get :favorites
      end
    end
    
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]do
       resources :comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy]
    end
    
    post "search" => "searches#search"
    get "search_tag"=>"posts#search_tag"
  end
  
  
  
#管理者側
  devise_for :admins, skip: [:registrations, :passwords], 
    controllers: {
    sessions: 'admins/sessions'
  }
  
  namespace :admins do
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
    
    resources :users, only:[:index, :show]
    resources :announcements, only:[:index, :new, :create, :show, :edit, :update, :destroy]
    resources :posts, only:[:index, :show, :destroy]do
      resources :comments, only: [:destroy]
    end
  end
  
  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :title, presence: true, on: :publicize
  validates :content, presence: true, on: :publicize
  
  
  has_one_attached :image
  has_many_attached :addition_images
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('hukucity/app/assets/images/no_image_irasutoya.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :image, presence: true, on: :publicize
  validate :validate_number_of_files
  
  def validate_number_of_files
    return if addition_images.length <= 4
    errors.add(:addition_images, "に入力できる画像は4つまでです。")
  end
  
  
  belongs_to :user
 
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, keyword)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{keyword}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{keyword}%")
    else
      @post = Post.all
    end
  end
  
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  
  def index
    @posts = Post.where(is_draft: :false).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
  end
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to admin_posts_path
    else
      render 'show'
    end
  end



end

app/controllers/publics/posts_controller.rb
class Publics::PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search_tag]
  
  
  def new
    @post = Post.new
  end
  
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #タグを作るには「,」をつける
    tag_list = params[:post][:name].split(',')
    
    #投稿公開
    if params[:release]
      @post.is_draft = false
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "投稿を公開しました！"
        redirect_to user_posts_path(current_user)
      else
        render :new
      end
    #下書き
    elsif params[:draft]
      @post.is_draft = true
      if @post.update(is_draft: :true)
        @post.save_tag(tag_list)
        flash[:notice] = "下書きを保存しました！"
        redirect_to confirm_user_path(current_user)
      else
        render :new
      end
    end
  end
  
  
  def index
    @posts = Post.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_tags = @post.tags
    @comment = Comment.new
  end


  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(',')
  end
  
  
  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].split(',')
      
  # ①下書きを公開する場合
    if params[:publicize_draft]
      @post.attributes = post_params.merge(is_draft: false)
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        flash[:notice] = "公開しました！"
        redirect_to user_posts_path(current_user)
      else
        @post.is_draft = true
        render :edit
      end
      
  # ②公開済みの投稿を更新する場合
    elsif params[:update_post]
      @post.attributes = post_params
      if @post.save(context: :publicize)
        @post.save_tag(tag_list)
        redirect_to user_posts_path(current_user)
      else
        render :edit
      end   
      
  # ③下書きを下書きに更新する場合
    else
      if @post.update(post_params)
        @post.save_tag(tag_list)
        redirect_to confirm_user_path(current_user)
      else
        render :edit
      end    
      
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "削除しました。"
      redirect_to posts_path, status: :see_other
    else
      render 'edit'
    end
  end
  
  
  def search_tag
    @tag_list = Tag.joins(posts: :user)#改行
                .merge(Post.where(is_draft: false)).merge(User.where(is_deleted: false)).distinct
    #検索されたタグを受け取る
    @tag = Tag.find(params[:tag_id])
    #検索されたタグに紐づく投稿を表示
    @posts = @tag.posts.where(is_draft: :false)#改行
                .joins(:user).merge(User.where(is_deleted: false)).order(created_at: :desc).page(params[:page]).per(8)
  end
  
  
  
   private
  
  def post_params
    params.require(:post).permit(:image, :title, :content, :is_draft, addition_images: [] )
  end
  
  
  
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

app/views/admins/posts/index.html.erb
 <div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4 class="mt-5" >ユーザーの公開済み投稿一覧</h4>
    </div>
  </div>  
     <div class="col-md-8 mt-2 mx-auto">
      
    <table class="table table-striped table-light table-hover">
     <% @posts.each do |post| %>
      <tr>
        <td>
          <%= link_to admin_post_path(post.id) do %>
            <% if post.image.attached? %>
             <%= image_tag post.image, size: "100x80" %>
            <% else %>
             <%= image_tag 'no_image_irasutoya', size: "100x80" %>
            <% end %>
          <% end %>
        </td>
        <td>
         <div class="d-flex flex-column">
          <div>
            <%= link_to admin_post_path(post.id), class: "text-dark text-decoration-none" do %>      
              <strong><%= post.title.truncate(20) %></strong><% end %>
          </div>
          <div>
            <% if post.user.profile_image.attached? %>
             <%= image_tag post.user.profile_image, size: "30x30", class:"mt-3 rounded-circle"; %>
            <% else %>
             <%= image_tag 'no_image_irasutoya', size: "30x30", class:"mt-3 rounded-circle"; %>
            <% end %>
            <small><%= post.user.nickname %>
               <% if post.user.is_deleted == true %><p class="text-danger">(退会)</p><% end %></small>
          </div>
         </div>
        </td>
        <td>
          <%= post.created_at.strftime('%Y/%m/%d') %>
        </td> 
      </tr>
     <% end %>
    </table>
     <%= paginate @posts %>
    </div>  
      
</div>
      

app/views/admins/posts/show.html.erb
  
 <div class='container'>
 
  <div class="row">
    <div class="col-lg-4 mt-5">
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, size: "50x50", class:"mt-3 rounded-circle"; %>
      <% else %>
        <%= image_tag 'no_image_irasutoya', size: "50x50", class:"mt-3 rounded-circle"; %>
      <% end %>
      
      <%= link_to admin_user_path(@user.id), class: "text-dark" do %>
          <%= @user.nickname %><% end %>
    </div>
    
    <div class="col-lg-2 offset-lg-6 mt-5" >
      <%= link_to "この投稿を削除する", admin_post_path(@post), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
    </div>
  </div>
   <div class="row mt-5">
    <div class="col-lg-5" > 
     <div class="swiper">
        <div class="swiper-wrapper">
           <div class="swiper-slide">
            <% if @post.image.attached? %>
              <%= image_tag @post.image, size: "420x420", class: 'd-block mx-auto img-fluid' %>
            <% else %>
              <%= image_tag 'no_image_irasutoya', size: "420x420", class: 'd-block mx-auto img-fluid' %>
            <% end %>
           </div>
            <% if @post.addition_images.attached? %>
              <% @post.addition_images.each do |addition_images| %>
               <div class="swiper-slide">
                <%= image_tag addition_images, size: "420x420", class: 'd-block mx-auto img-fluid' %>
               </div>
              <% end %>
            <% end %>
        </div>
          <div class="swiper-pagination"></div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
      </div>
           <table class="table mt-3"> 
        <% @post.comments.each do |comment| %>
         <tr>
          <td>
            <% if comment.user.profile_image.attached? %>
             <%= image_tag comment.user.profile_image, size: "50x50", class:"mt-3 rounded-circle"; %>
            <% else %>
             <%= image_tag 'no_image_irasutoya', size: "50x50", class:"mt-3 rounded-circle"; %>
            <% end %>
          </td>
          <td>
            <div class="d-flex flex-column">
              <div>
                <%= comment.user.name %>
                <small><%= comment.created_at.strftime('%Y/%m/%d') %></small>
              </div>
              <div>
                <%= comment.comment %>
              </div>
          </td>
          <td>
            <%= link_to "コメント削除", admin_post_comment_path(comment.post.id, comment.id), method: :delete,
                      class: "btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %>
          </td>
         </tr>    
        <% end %>
      </table> 
    </div>
     <div class="col-lg-7 p-5" >
      <h4>【<%= @post.title %>】</h4>
      <div>
        <% @post_tags.each do |tag| %>
          <i class="fa-sharp fa-solid fa-tag"> <%= tag.name %></i>
        <% end %>
      </div>
      <p><%= h(@post.content).gsub(/\n|\r|\r\n/, "<br>").html_safe %></p>
    </div>
    
  </div> 
</div>
    

<script>
  const swiper = new Swiper('.swiper', {
    //オプションの設定
    loop: true,
   
    //ページネーション表示の設定
    pagination: { 
      el: '.swiper-pagination', //ページネーションの要素
    },
   
    //ナビゲーションボタン（矢印）表示の設定
    navigation: { 
      nextEl: '.swiper-button-next', //「次へボタン」要素の指定
      prevEl: '.swiper-button-prev', //「前へボタン」要素の指定
    }
  });
</script>