config/routes.rb
Rails.application.routes.draw do

#ゲストログイン 
  devise_scope :user do
    get 'user/guest_sign_in', to: 'publics/sessions#guest_sign_in'
  end
 
 
#ユーザー側
  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'publics/sessions',
    registrations: 'publics/registrations'
  }
  
  #退会確認画面
  get '/users/:id/unsubscribe' => 'publics/users#unsubscribe', as: 'unsubscribe'
  #論理削除用のルーティング
  patch '/users/:id/withdrawal' => 'publics/users#withdrawal', as: 'withdrawal'

  root to: 'publics/homes#top'
  get '/announcements' => 'publics/homes#announcements'
  scope module: :publics do
    resources :users, only:[:index, :show, :edit, :update] do
      resources :posts, only:[:index]
      member do
        get :confirm
        get :favorites
      end
    end
    
    resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy]do
       resources :comments, only: [:create, :destroy]
       resource :favorites, only: [:create, :destroy]
    end
    
    post "search" => "searches#search"
    get "search_tag"=>"posts#search_tag"
  end
  
  
  
#管理者側
  devise_for :admins, skip: [:registrations, :passwords], 
    controllers: {
    sessions: 'admins/sessions'
  }
  
  namespace :admins do
    patch "withdrawal/:id" => "users#withdrawal", as: "withdrawal"
    
    resources :users, only:[:index, :show]
    resources :announcements, only:[:index, :new, :create, :show, :edit, :update, :destroy]
    resources :posts, only:[:index, :show, :destroy]do
      resources :comments, only: [:destroy]
    end
  end
  
  
 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/announcement.rb
class Announcement < ApplicationRecord
  
  has_one_attached :announcement_image
  
  validates :title, presence: true
  validates :announcement_image, presence: true
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :post_id, uniqueness: { scope: :user_id }
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :title, presence: true, on: :publicize
  validates :content, presence: true, on: :publicize
  
  
  has_one_attached :image
  has_many_attached :addition_images
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('hukucity/app/assets/images/no_image_irasutoya.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  validates :image, presence: true, on: :publicize
  validate :validate_number_of_files
  
  def validate_number_of_files
    return if addition_images.length <= 4
    errors.add(:addition_images, "に入力できる画像は4つまでです。")
  end
  
  
  belongs_to :user
 
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def save_tag(sent_tags)
  # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      self.tags << new_post_tag
   end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, keyword)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{keyword}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?","%#{keyword}%")
    else
      @post = Post.all
    end
  end
  
  
end

app/models/profile_image.rb
class PoImage < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :tag_maps,dependent: :destroy, foreign_key: 'tag_id'
  
  has_many :posts,through: :tag_maps
  
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  
  belongs_to :post
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲスト'
      user.name_kana = 'ゲスト' 
      user.nickname = 'ゲスト'
      user.telephone_number = '00000000001' 
    end
  end
  
  #退会済みユーザーのログイン制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  validates :name, presence: true
  validates :name_kana, presence: true, format: { with: /\A[ァ-ヴー]+\z/u }
  validates :nickname, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  
  

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('hukucity/app/assets/images/no_image_irasutoya.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  
  def self.looks(search, keyword)
    if search == "perfect_match"
      @user = User.where("nickname LIKE?", "#{keyword}")
    elsif search == "partial_match"
      @user = User.where("nickname LIKE?","%#{keyword}%")
    else
      @user = User.all
    end
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
 
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publics/comments_helper.rb
module Publics::CommentsHelper
end

app/helpers/publics/homes_helper.rb
module Publics::HomesHelper
end

app/helpers/publics/posts_helper.rb
module Publics::PostsHelper
end

app/helpers/publics/searches_helper.rb
module Publics::SearchesHelper
end

app/helpers/publics/users_helper.rb
module Publics::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <ul>
      <% model.errors.full_messages_for(attribute).each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/_header.html.erb
 <% if admin_signed_in? %>
    <li class="nav-item mx-2">
      <%= link_to "お知らせの掲示／一覧", admins_announcements_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "ユーザーの投稿管理", admins_posts_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "ユーザー一覧", admins_users_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
    </li>
    
  <% elsif user_signed_in? %>
  <div class="d-flex flex-column mb-3">
   <div class="d-flex flex-row-reverse p-2">
    <li class="nav-item mx-2">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to 'マイページ', user_path(current_user.id) %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to 'ユーザー一覧', users_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to 'みんなの投稿をみる', posts_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to 'アイデアを投稿する', new_post_path %>
    </li>
   </div>
   <div class="text-right p-2"> 
     <%= form_with url: search_path, local: true, class: "rootpageSearchForm" do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワードを入力", class: "rootpageSearchForm__content" %>
      <%= f.select :range, options_for_select([['ユーザー名'], ['投稿タイトル']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "rootpageSearchForm__bottum" %>
     <% end %>
   </div>
  </div> 
  
  <% else %>
    <li class="nav-item mx-2">
      <%= link_to '投稿一覧をみる', posts_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "新規登録", new_user_registration_path %>
    </li>
    <li class="nav-item mx-2">
      <%= link_to "ユーザーログイン", new_user_session_path %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hukucity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    
    <script src="https://kit.fontawesome.com/86b1bf15ce.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>
  
<body>
  <header>
    <nav class = "navbar navbar-expand-lg navbar-light  border-black border-bottom p-4">
      <div class = "container">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "logo.png", style: "width: 150px; height: 150px;"%>
          <% end %>
          
          <% if user_signed_in? %>
              ようこそ、<%= current_user.nickname %>さん！
          <% end %>
          
          <ul class = "navbar-nav ml-auto">
            <%= render "layouts/header" %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
   <main>
    <%= yield %>
  </main>
  <footer class="border-top pt-5"></footer>
 </body>
</html>

 